/**
 * AERTH BUNDLER - Export a wallet's real seed phrase / private key
 *
 * Wallets on disk are AES-encrypted (WALLET_ENCRYPTION_PASSWORD). This
 * decrypts one and prints it in formats a real wallet app (Phantom, etc.)
 * can import directly:
 *   - Seed phrase (only exists for wallets generated by this app - the main
 *     wallet, if imported via MAIN_WALLET_PRIVATE_KEY in .env, was never
 *     generated from a mnemonic and has no seed phrase, only a private key)
 *   - Private key as base58 (Phantom's "Import Private Key" expects base58,
 *     not the base64 this app stores internally)
 *
 * Usage:
 *   npx tsx src/scripts/exportWallet.ts main [--mainnet]
 *   npx tsx src/scripts/exportWallet.ts 3 [--mainnet]     (sub-wallet index 3)
 * Defaults to the devnet wallet folder; pass --mainnet for the mainnet one.
 */
import bs58 from 'bs58';
import dotenv from 'dotenv';
import { WalletManager } from '../core/walletManager';
import { log } from '../utils/logger';
import { resolveWalletFolder } from '../config/constants';

dotenv.config();

if (process.argv.includes('--mainnet')) {
  process.env.NETWORK = 'mainnet';
} else if (process.argv.includes('--devnet')) {
  process.env.NETWORK = 'devnet';
}

async function exportWallet() {
  const target = process.argv[2];
  if (!target) {
    log.error('Usage: npx tsx src/scripts/exportWallet.ts <main|wallet-index> [--mainnet]');
    process.exit(1);
  }

  const wm = new WalletManager(null as any, process.env.WALLET_ENCRYPTION_PASSWORD || 'default_password', resolveWalletFolder());
  await wm.initialize();
  await wm.loadWallets();

  const wallet = target === 'main'
    ? wm.getMainWallet()
    : wm.getWallets().find(w => w.index === parseInt(target, 10));

  if (!wallet) {
    log.error(`Wallet not found: ${target}`);
    process.exit(1);
  }

  const privateKeyBase58 = bs58.encode(Buffer.from(wallet.privateKey, 'base64'));

  console.log('\n⚠️  SENSITIVE - do not share this output or paste it anywhere untrusted.\n');
  console.log(`  Public Key:            ${wallet.publicKey}`);
  console.log(`  Seed Phrase:           ${wallet.seedPhrase || '(none - this wallet was imported from a raw private key, not generated from a mnemonic)'}`);
  console.log(`  Private Key (base58):  ${privateKeyBase58}`);
  console.log('\nIn Phantom: Settings -> Add/Connect Wallet -> Import Private Key, paste the base58 key above.');
  console.log('(Or "Import Seed Phrase" if a seed phrase was shown above.)\n');
}

exportWallet().catch(console.error);
